title: Блог о Front-end'е
sub_title: Записки сумасшедшего новичка
description: Небольшой блог в котором собран
             путь молодого начинающего разработчика в постижении великих 
             знаний фронтенда. Цель - устаканить свои знания  и 
             передать их всем кому они пригодяться. Возможно, в будущем, стать 
             гуру этой великой и необьятной науки. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
lang: ru-RU
instagram: https://www.instagram.com/wnetking/
email: wnetking1@gmail.com
github: https://github.com/wnetking
facebook: https://www.facebook.com/wnetking
linkedin: https://www.linkedin.com/in/illya-kyrylov-175a85123/