title: Блог про Front-end
sub_title: Записки сумашедшего новичка
description: Небольшой блог в котором собран
              путь молодого начинающего разработчика в постижении великих 
    знаний фронтенда. Цель - стать гуру этой великой науки и 
    передать знания всем кому они пригодяться.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman